name: Lint and test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pipeline:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: StyLua
      uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.20.0
        args: --check .
    - name: Busted
      uses: lunarmodules/busted@02f31a9c103a44e166617cfdb6ba1b8994a9c912 # v2.2.0
